= A greener Redlands
:page-last_modified_at: 2025-03-30
:page-excerpt: This purpose of this proposal is to persuade the city of Redlands, California to install solar panels on municipal buildings, such as the Redlands City Hall. This investment will benefit  the Redlands community and the surrounding ecosystem by increasing energy resiliency and decreasing the city’s carbon footprint. As members of the community and of a warming planet, we want to improve our city’s access to sustainable, clean energy. We urge Redlands leadership to take this action in the face of economic, environmental, and political instability.
:icons: font

****
For my PTW320 portfolio project, I created a mock proposal to install solar panels on city buildings. I chose Redlands, California city council members as my audience. I assumed this audience’s top task is to act in the best interest of their community. To help them do that, this proposal explains why solar panels decreases their constituents’ carbon footprint and improves the city’s energy resiliency.

I chose a long-form deliverable for this project. This let me practice a different writing format than what I typically write. Whereas my previous portfolio projects were instructional, this deliverable needed to persuade its audience. This difference made me think about structure and information delivery in new ways. This project also needed more background research than a typical how-to guide. This persuasive writing and research exercise was rewarding for me.

The project’s short time frame meant compromises with the content. The organization would have been improved by talking to someone with more city planning experience. That subject matter expert feedback is crucial to fill the gaps in my domain knowledge. With more time, I would have expanded on the cost and benefits section as well.

This was a refreshing change of pace. I’m happy with the exposure to a new kind of writing that it gave me.
****

NOTE: This is a mock proposal. The content is for educational and professional development purposes only.

This purpose of this proposal is to persuade the city of Redlands, California to install solar panels on municipal buildings, such as the Redlands City Hall. This investment will benefit  the Redlands community and the surrounding ecosystem by increasing energy resiliency and decreasing the city’s carbon footprint. As members of the community and of a warming planet, we want to improve our city’s access to sustainable, clean energy. We urge Redlands leadership to take this action in the face of economic, environmental, and political instability.

== Current state of power and resiliency in Redlands

Redlands, California residents pay https://www.energysage.com/local-data/electricity-cost/ca/san-bernardino-county/redlands/[24% more than the national average for electricity]. One reason is the area’s hot climate. https://weatherspark.com/y/1965/Average-Weather-in-Redlands-California-United-States-Year-Round[The hottest month of the year in Redlands, August, averages 95°F]. Hot temperatures drive residents and city staff to spend more money on interior cooling systems.

Not only are these systems costly; they are environmentally destructive. Today, cooling contributes https://www.unep.org/news-and-stories/story/air-conditioners-fuel-climate-crisis-can-nature-help[seven per cent of global greenhouse gas emissions]. Experts in the field expect this number to https://www.iea.org/energy-system/buildings/space-cooling[double by 2030 and triple by 2050]. Cooling systems drive a negative feedback loop. As communities continue to depend on their traditional cooling systems, they continue to pollute. The more they pollute, the more they destabilize the climate. As the climate is further disrupted, temperatures rise to higher and higher degrees, which increases a community's cooling system dependence.

Redlands' energy sources for powering those cooling systems compound the problem. Roughly https://wattbuy.com/en/electricity-rates/california/redlands/[43% of Redlands’s energy comes from natural gas]. Natural gas is a major greenhouse gas emission source. It can also be unreliable in emergencies. Like other Southern Californian cities, Redlands is under constant threat of powerful earthquakes from the San Andreas fault. A recent https://pubs.usgs.gov/fs/2015/3009/pdf/fs2015-3009.pdf[USGS report] suggests a 93% likelihood of one or more 6.7 magnitude earthquakes in the next 30 years. Over this same time span, the report suggests a 75% likelihood of one or more seven magnitude earthquakes. These massive earthquakes can potentially disrupt power supply to entire communities. Communities that are not ready may have trouble restoring power, which https://www.poweroad.com/knowledges/how-to-get-reliable-power-supply-when-power-outages-occur-in-earthquakes/[can cause major property damage and safety risks]. The city’s solar energy production, 31% of total production, is not far behind. Still, Redlands must keep improving until greenhouse gas emitting energy sources are not the plurality.

Redlands must invest in new solutions to improve the city's environmental position. Our solution is for the city to lead the charge by installing solar panels on municipal buildings, such as Redlands City Hall.

== Project plan to install solar panels on Redlands City Hall

With this proposal, we ask the Redlands city leadership to commit to its sustainability plans, as laid out in the https://www.cityofredlands.org/sites/main/files/file-attachments/redlandsstrategicplan_final.pdf?1651172526[City of Redlands Strategic Plan for 2022 to 2028].

The city can do so in three steps:

=== Part 1: Assess City Hall's readiness for solar panels

To assess City Hall's readiness for solar panels, the city must answer the following questions:

* Is the roof flat or angled?
* Is the roof shaded or obstructed?
* Can the solar panels extend over other areas of the property, such as parking lots or an adjacent land lot?

By addressing these questions, the city can prepare project budgets and schedules.

=== Part 2: Install solar panels

With these preparations in place, the city can plan the installation. Many companies in Southern California can help, including:

* https://www.energysage.com/supplier/21398/solar-optimum/[Solar Optimum]: Solar Optimum was the 2024 Installer of the Year, according to https://www.energysage.com/[EnergySage]. Established in 2008, they continue to lead the solar industry across California, Nevada, Arizona, and Florida.
* https://www.energysage.com/supplier/20701/nrg-clean-power/[NRG Clean Power]: NRG Clean Power is the leading solar installer in California and Texas. Two of their core tenets about electricity are that it should be renewable and affordable.
* https://www.energysage.com/supplier/26285/integratesun-llc/[IntegrateSun, LLC]: IntegrateSun installs the same technology that NASA uses for their space stations.

City leadership must assess providers, estimated costs, and projected timelines. The city can request quotes from the above providers to compare options. Include any findings from the initial assessment in the quote request.

=== Part 3: Inspect the installation for safety and quality

An independent party must inspect newly installed solar panels. The inspector looks for:

* Safety issues.
* Potential shorts in the wiring.
* The physical structure to confirm the panels will survive environmental conditions.

This inspection ensures the installation is complete and safe.

== Costs and benefits of installing solar panels

It is important to understand the total costs of installing solar panels. In Redlands, the https://wattbuy.com/en/solar/california/redlands/[average solar panel installation costs roughly $14,000], after federal incentives. Another cost is installation time. Installing solar panels can https://www.solarreviews.com/blog/solar-panel-installation-process[take between two and six months] between:

* Finding the right solar company
* Drafting and approving contracts
* Physically installing panels
* Completing comprehensive inspections

Furthermore, Redlands City Hall's https://www.energysage.com/solar/installing-solar-panels-on-different-roof-types/solar-flat-roofs-top-3-things-need-know/[flat roof can increase the installation costs]. These costs are significant, but so are the benefits the city will enjoy.

These benefits include:

* Solar panels in Southern California, on average, https://wattbuy.com/en/solar/california/redlands/[pay for themselves in five years].
* In the event of an earthquake, Redlands City Hall can continue operating and aiding the community.
* Increasing green energy's percentage of energy generation means less greenhouse gases and a healthier environment.

By approving this proposal, you will not only improve Redlands's energy portfolio; you will also decrease Redlands's carbon footprint. As our carbon footprint becomes more critical to consider, these kinds of proposed initiatives become more important. Redlands owes it to its community to lead the way in green energy initiatives.

Thank you for considering this proposal. We are looking forward to discussing the matter further and are awaiting your decision.

