= README driven development
:page-last_modified_at: 2025-05-14
:page-categories: [articles]
:url-1: https://tom.preston-werner.com/2010/08/23/readme-driven-development
:url-2: https://www.oreilly.com/library/view/clean-code-a/9780136083238/
:url-3: https://github.com/resources/articles/software-development/innersource
:url-4: https://www.agilealliance.org/agile101/

I recently read an {url-1}[article by Tom Preston-Werner] about how to solve the undocumented project problem—how do you promote a project when no one knows what it does? Then, I saw this article and Preston-Werner's solution everywhere. His solution is README Driven Development (RDD).

In RDD, you start your project with the README file. This makes you plan out your project before you even start writing any code. By creating the README first, you have to think about how you use it, how others use it, and how anyone can contribute to it. Your project becomes more streamlined from the beginning. RDD also means your project starts with a solid foundation in terms of documentation. Rather than creating your documentation after the fact, you start with a document that evolves as the project evolves. That's much easier than trying to remember every implementation detail after you've pushed the entire project.

In this article, I discuss how RDD compares to other "driven development" strategies, its pros and cons,  and my own experience with it.

pass:[<!-- vale Microsoft.Headings = NO -->]

== The historical context of README Driven Development

The software development world has seen many "driven development" strategies. Some examples are Test Driven Development (TDD), Design or Document Driven Development (DDD), and Bug Driven Development (BDD). They describe a mindset that software developers adopt to create good products. Typically, they stress the importance of one component of the development cycle, like test suites or bug catches. This component becomes the driving force behind the whole endeavor. These kinds of software development strategies have been around for ages. I first read about one of them—Test Driven Development—in Robert Martin's {url-2}[_Clean Code: A Handbook of Agile Software Craftsmanship_]. Since then, I've seen all kinds of variations.

How does RDD fit into this group of development strategies? Rather than tests or bugs, RDD focuses on a project's documentation. Specifically, it applies to open source or {url-3}[innersource] projects that have their documentation as their landing page for new users. RDD, like the types of projects it serves, leaves room for flexibility. RDD starts with the documentation, called the README, it lets the documentation evolve as the project evolves. In that way, it fits well with other methodologies that other driven development strategies use, like {url-4}[Agile].

== Pros and cons of README Driven Development

RDD has many perks, including:

* It improves your project plan
+
--
When you start with the README, you must think about how your project works before you write a line of code. A README covers what your project does and how to run it. If you already have a plan for these, it gives you a roadmap for how to structure the project's code. The result is a coherent codebase that's quick to learn and easy to extend.
--
+
* It makes it easy for others to contribute
+
--
A clear README opens the door for other developers to add to your project. The first step to contributing to any project is to learn the setup. Only when a developer understands how the project's pieces fit together can they suggest improvements. If you want to attract more contributors, then you need to cut down the required study time. This is where a well-written README comes in handy. Your README documentation is where you describe how your project works. If your README describes the project in plain language, then others can see how and where to contribute without digging through the raw code.
--
+
* It keeps the documentation up to date
+
--
It's harder to write documentation for a finished project than to update documentation as a project grows. If you start your project with a well-written README document, then you can update it as you update the source code. Otherwise, you have to remember all the details hours or days after you wrote the code and published the project. Often, projects end up with no documentation, at all.
--

On the other hand, has its drawbacks. With RDD, you're writing about what you want to build, rather than just building it. Then you have to hold yourself back—even after hyping of the project, RDD says you have to write the README first. It's a practice of delayed gratification. Not only is it delayed gratification, it's often not comfortable for developers to write this way. They think more in code than in words. Despite the typical job requirements for software engineers that include "communication skills," most engineers get by with minimal written documentation.

This is, of course, an issue. But it's one that can be overcome with practice and training. Developers learn that putting their ideas on paper—or on screen—means they spend less time trying different strategies or changing interfaces. They also learn that the coding experience is smoother when you have a rough plan laid out for you. And everyone else in the development cycle benefits from clear documentation.

== My README Driven Development experience

pass:[<!-- vale Microsoft.Headings = YES -->]

== Conclusion
