= Plain English editing
:page-last_modified_at: 2025-06-10
:page-categories: ["portfolio"]

++++
<script src="/assets/scripts/pdf_download_script.js"></script>
++++

== Exercise 1

In each sentence, underline the subject once and the verb twice. Is the subject abstract or concrete? Rewrite the sentences choosing concrete nouns as subjects and making their actions the verbs.

. [.underline]#Processes# undertaken by diverse plants and animals [.doubleunderline]#are# responsible for such ecological actions as nutrient cycling, carbon storage, and atmospheric regulation.
+
--
The subject, _Processes_, is abstract.

.My revision
[%collapsible]
====
Diverse [.underline]#plants and animals# [.doubleunderline]#perform# ecological actions such as nutrient cycling, carbon storage, and atmospheric regulation.
====

.Solution
[%collapsible]
====
An [.underline]#ecosystem# of diverse plants and animals [.doubleunderline]#cycles# nutrients, [.doubleunderline]#stores# carbon, and [.doubleunderline]#regulates# the atmosphere.
====
--
+
. [.underline]#Declines# in birth rates [.doubleunderline]#have been observed# in many developed countries, and demographers expect that the transition to a stable population will eventually occur in many undeveloped nations as well.
+
--
The subject, _Declines_, is abstract.

.My revision
[%collapsible]
====
[.underline]#Demographers# [.doubleunderline]#have observed# declines in birth rates in many developed countries. [.underline]#They# [.doubleunderline]#expect# the same to happen eventually in undeveloped nations as well.
====

.Solution
[%collapsible]
====
[.underline]#Demographers# [.doubleunderline]#have observed# that birth rates are declining in many developed countries. They [.doubleunderline]#expect# that populations will eventually stabilize as birth rates decline in undeveloped countries as well.
====
--
+
. [.underline]#Variations# in magmatism during rifting [.doubleunderline]#have been attributed# to variations in mantle temperature, rifting velocity or duration, active upwelling, or small-scale convection.
+
--
The subject, _Variations_ is abstract.

.My revision
[%collapsible]
====
During rifting, [.underline]#magmatism# [.doubleunderline]#changes# according to changes in mantle temperature, speeds and durations of rifting, movements of magma, and transfers of heat.
====

.Solution
[%collapsible]
====
[.underline]#Magma# produced during rifting [.doubleunderline]#varies# for several reasons: changes in mantel temperature, rifting velocity or duration, active upwelling, or small-scale convection.
====
--
+
. The [.underline]#inability# of lateral variations in mantle temperature and composition, alone, to account for our observations [.doubleunderline]#leads# us to propose that another influence was melt focusing.
+
--
The subject, _inability_, is abstract.

.My revision
[%collapsible]
====
[.underline]#We# could not [.doubleunderline]#attribute# our observations to only lateral differences in mantel temperature and composition. [.underline]#We# [.doubleunderline]#propose# melt focusing as another influence on our observations.
====

.Solution
[%collapsible]
====
[.underline]#We# [.doubleunderline]#could# not [.doubleunderline]#account# for our observations with lateral variations in mantle temperatures and composition alone. Another [.underline]#influence# [.doubleunderline]#was# melt focusing.
====
--
+
. The [.underline]#ability# of mudrock seals to prevent CO~2~ leakage [.doubleunderline]#is# a major concern for geological storage of anthropogenic CO~2~.
+
--
The subject, _ability_, is abstract.

.My revision
[%collapsible]
====
Mudrock [.underline]#seals# [.doubleunderline]#can prevent# CO~2~ leakage and thus can add to the geological storage of anthropogenic CO~2~.
====

.Solution
[%collapsible]
====
[.underline]#Geologists# [.doubleunderline]#are concerned# that mudrock seals may allow anthropogenic CO~2~ to leak from geological storage.
====
--

== Exercise 2

In each sentence, underline the main verb twice. Revise the sentences by substituting strong verbs for weak verbs. Replace abstract nouns where you can.

. Photographs from space taken by satellites [.doubleunderline]#are# indicators of urbanization and just one of the demonstrations of the human footprint.
+
--
.My revision
[%collapsible]
====
Photographs from space taken by satellites indicate urbanization and demonstrate the human footprint on the planet.
====

.Solution
[%collapsible]
====
Satellite photographs indicate the spread of urban areas and demonstrate the human footprint.
====
--
+
. Weather variables (precipitation, temperature, and wind speed) [.underline]#are# key factors in limiting summer habitat availability.
+
--
.My revision
[%collapsible]
====
====
--
+
. A risk management ranking system is the central mechanism for which prioritization of terrestrial invasive species is based.
. It is clear that Prairie Chickens are closely associated with sagebrush habitat throughout the year.
. The occurence of freesing and thawing is an important control on cohesive bank erosion in the region.

== Exercise 3

In each sentence, underline the subject once and the verb twice. Revise by placing the subject and the verb close together. Replace abstract nouns where you can.

. Environmentally sensitive solutions to the problems associated with continued population growth and development will require an environmentally literate citizenry.
. Partnerships between professional teachers, scientists, non-professional science educators, and administrators are needed to improve the content and effectiveness of science education, particularly in rural areas.
. Our ability to predict the spatial spread of exotic species and their transformation of natural communities is still developing.
. The amount of magmatism that accompanies the extension and rupture of the continental lithosphere varies dramatically at rifts and margins around the world.
. Pre-migration of melts vertically to the top of the melting region and then laterally along the base of the extended continental lithosphere would focus melts toward the eastern part of the basin.
. Pre-treatment of tenocytes with different concentrations of wortmannin (1, 10, and 20 nM) for 1 h, treated with curcumin (5 μM) for 4 h, and then treated with IL-1β-induced NF-κB activation.
