= README driven development
:page-categories: [articles]

In README driven development (RDD), you start your project with the README file. This makes you plan out your project before you even start writing any code. By creating the README first, you have to think about how you'll use it, how others will use it, and how anyon can contribute to it. Your project ends up more streamlined from the beginnning. RDD alsdo means your project starts with a solid foundation as far as documentation is concerned. Rather than creating your documetnation after the fact, you start with a solid document that can evolve as the project evolves. Maintaining a document is much easier than going back and tyrying to remembert every implementaiton detail after you've pushed the entire project.

In this article, we'll explore the pros and cons of RDD, how it compares to other "driven development" strategies, and my own experience with it.

== RDD pros and cons

== RDD's historical context

== My RDD experience

== Conclusion
