= _Searches_: A glimpse into and a warning of the singularity
:page-last_modified_at: 2025-04-30
:book-title: Searches
:book-subtitle: Selfhood in the Digital Age
:page-categories: [book-reviews]
:page-excerpt: A glimpse into and a warning of the singularity
:url-book: https://www.penguinrandomhouse.com/books/745381/searches-by-vauhini-vara/

{url-book}[_Searches: Selfhood in the Digital Age_] by Vauhini Vara (Pantheon, 2025) explores how to be human in an AI age. Vara talks about how we give our language, our attention, and our experiences to Big Tech. What we're left with is a sense that it's too late to take any of it back. Even if we could, we wouldn't want to.

image::https://images4.penguinrandomhouse.com/cover/9780593701522["Searches book cover"]

Vara made me think. What, truly, do we give to Altman and Musk and the other technocrats? Her conversations with ChatGPT haunted me. The model's contributions stank of AI but Vara spun gold from it. I've never seen an author use it like that, so in the open for all to see.

I recommend reading this one. The experience is worth it. Her writing style is clear and crisp. I want to read her fiction, whatever had won her the Pulitzer. I hope to get more books about AI and it's impacts in the future, and I hope they're as good as this one.

