= Writing in Plain English
:page-last_modified_at: 2025-06-12
:page-liquid:
:page-categories: ["portfolio"]
:page-toc: true
:page-toc_label: "Table of contents"
:page-toc_icon: "cog"
:page-toc_sticky: true

== Introduction

Technical writers want to write in a way that best serves their readers: they replace weak verbs with strong verbs, switch passive voice to active voice, and rewrite complex sentences into simple ones. Together, these rules guide technical writers towards a consistent style that's easy to read and understand. Writers call this style Plain English.

But what exactly does Plain English mean? To learn more, I read the latest edition of Anne Greene's classic book, _Writing Science in Plain English_. Plain English demands short, simple words and clear sentences. This creates texts that can clearly explain any kind of complex topic beyond just science. And that makes the style worth using for any writer.

To help readers learn to use Plain English, Greene includes exercises throughout her book. For each exercise, I wrote my answer and included Greene's answer as well. I then compared our answers to see how we arrived at our new sentences. By doing so, I hope to improve my Plain English skills and write clearer content.

== Exercise 1

In each sentence, underline the subject once and the verb twice. Is the subject abstract or concrete? Rewrite the sentences choosing concrete nouns as subjects and making their actions the verbs.

. [.underline]#Processes# undertaken by diverse plants and animals [.doubleunderline]#are# responsible for such ecological actions as nutrient cycling, carbon storage, and atmospheric regulation.
+
--
The subject, _Processes_, is abstract.

.My revision
[%collapsible]
====
Diverse [.underline]#plants and animals# [.doubleunderline]#perform# ecological actions such as nutrient cycling, carbon storage, and atmospheric regulation.
====

.Solution
[%collapsible]
====
An [.underline]#ecosystem# of diverse plants and animals [.doubleunderline]#cycles# nutrients, [.doubleunderline]#stores# carbon, and [.doubleunderline]#regulates# the atmosphere.
====
--
+
. [.underline]#Declines# in birth rates [.doubleunderline]#have been observed# in many developed countries, and demographers expect that the transition to a stable population will eventually occur in many undeveloped nations as well.
+
--
The subject, _Declines_, is abstract.

.My revision
[%collapsible]
====
[.underline]#Demographers# [.doubleunderline]#have observed# declines in birth rates in many developed countries. [.underline]#They# [.doubleunderline]#expect# the same to happen eventually in undeveloped nations as well.
====

.Solution
[%collapsible]
====
[.underline]#Demographers# [.doubleunderline]#have observed# that birth rates are declining in many developed countries. They [.doubleunderline]#expect# that populations will eventually stabilize as birth rates decline in undeveloped countries as well.
====
--
+
. [.underline]#Variations# in magmatism during rifting [.doubleunderline]#have been attributed# to variations in mantle temperature, rifting velocity or duration, active upwelling, or small-scale convection.
+
--
The subject, _Variations_ is abstract.

.My revision
[%collapsible]
====
During rifting, [.underline]#magmatism# [.doubleunderline]#changes# according to changes in mantle temperature, speeds and durations of rifting, movements of magma, and transfers of heat.
====

.Solution
[%collapsible]
====
[.underline]#Magma# produced during rifting [.doubleunderline]#varies# for several reasons: changes in mantel temperature, rifting velocity or duration, active upwelling, or small-scale convection.
====
--
+
. The [.underline]#inability# of lateral variations in mantle temperature and composition, alone, to account for our observations [.doubleunderline]#leads# us to propose that another influence was melt focusing.
+
--
The subject, _inability_, is abstract.

.My revision
[%collapsible]
====
[.underline]#We# could not [.doubleunderline]#attribute# our observations to only lateral differences in mantel temperature and composition. [.underline]#We# [.doubleunderline]#propose# melt focusing as another influence on our observations.
====

.Solution
[%collapsible]
====
[.underline]#We# [.doubleunderline]#could# not [.doubleunderline]#account# for our observations with lateral variations in mantle temperatures and composition alone. Another [.underline]#influence# [.doubleunderline]#was# melt focusing.
====
--
+
. The [.underline]#ability# of mudrock seals to prevent CO~2~ leakage [.doubleunderline]#is# a major concern for geological storage of anthropogenic CO~2~.
+
--
The subject, _ability_, is abstract.

.My revision
[%collapsible]
====
Mudrock [.underline]#seals# [.doubleunderline]#can prevent# CO~2~ leakage and thus can add to the geological storage of anthropogenic CO~2~.
====

.Solution
[%collapsible]
====
[.underline]#Geologists# [.doubleunderline]#are concerned# that mudrock seals may allow anthropogenic CO~2~ to leak from geological storage.
====
--

== Exercise 2

In each sentence, underline the main verb twice. Revise the sentences by substituting strong verbs for weak verbs. Replace abstract nouns where you can.

. Photographs from space taken by satellites [.doubleunderline]#are# indicators of urbanization and just one of the demonstrations of the human footprint.
+
--
.My revision
[%collapsible]
====
Photographs from space taken by satellites [.doubleunderline]#indicate# urbanization and [.doubleunderline]#demonstrate# the human footprint on the planet.
====

.Solution
[%collapsible]
====
Satellite photographs [.doubleunderline]#indicate# the spread of urban areas and [.doubleunderline]#demonstrate# the human footprint.
====
--
+
. Weather variables (precipitation, temperature, and wind speed) [.doubleunderline]#are# key factors in limiting summer habitat availability.
+
--
.My revision
[%collapsible]
====
Precipitation, temperature, and wind speed [.doubleunderline]#limit# available summer habitat.
====

.Solution
[%collapsible]
====
Precipitation, temperature, and wind speed [.doubleunderline]#limit# available summer habitat.
====
--
+
. A risk management ranking system [.doubleunderline]#is# the central mechanism for which prioritization of terrestrial invasive species is based.
+
--
.My revision
[%collapsible]
====
A risk management ranking system [.doubleunderline]#prioritizes# terrestrial invasive species.
====

.Solution
[%collapsible]
====
We [.doubleunderline]#rank# terrestrial invasive species according to the threat they pose to the environment.
====
--
+
. It [.doubleunderline]#is# clear that Prairie Chickens are closely associated with sagebrush habitat throughout the year.
+
--
.My revision
[%collapsible]
====
Prairie Chickens [.doubleunderline]#live# in sagebrush habitat throughout the year.
====

.Solution
[%collapsible]
====
Prairie Chickens [.doubleunderline]#occupy# sagebrush habitat throughout the year.
====
--
+
. The occurence of freezing and thawing [.doubleunderline]#is# an important control on cohesive bank erosion in the region.
+
--
.My revision
[%collapsible]
====
Freezing and thawing [.doubleunderline]#control# cohesive bank erosion in the region.
====

.Solution
[%collapsible]
====
Freezing and thawing [.doubleunderline]#control# cohesive bank erosion in the region.
====
--

== Exercise 3

In each sentence, underline the subject once and the verb twice. Revise by placing the subject and the verb close together. Replace abstract nouns where you can.

. Environmentally sensitive [.underline]#solutions# to the problems associated with continued population growth and development [.doubleunderline]#will require# an environmentally literate citizenry.
+
--
.My revision
[%collapsible]
====
[.underline]#We# [.doubleunderline]#will require# environmentally literate citizens to find environmentally sensitive solutions to the problems of our continuously growing and developing population.
====

.Solution
[%collapsible]
====
To develop sustainable solutions to the problems of human growth and development, [.underline]#we# [.doubleunderline]#will need# environmentally literate citizens.
====
--
+
. [.underline]#Partnerships# between professional teachers, scientists, non-professional science educators, and administrators [.doubleunderline]#are# needed to improve the content and effectiveness of science education, particularly in rural areas.
+
--
.My revision
[%collapsible]
====
[.underline]#Scientists and science educators# [.doubleunderline]#must work# together to improve science education, particularly in rural areas.
====

.Solution
[%collapsible]
====
By building partnerships between professional teachers, scientists, nonprofessional science educators, and administrators, [.underline]#we# [.doubleunderline]#can improve# the content and effectiveness of science education, particularly in rural areas.
====
--
+
. Our [.underline]#ability# to predict the spatial spread of exotic species and their transformation of natural communities [.underline]#is# still developing.
+
--
.My revision
[%collapsible]
====
[.underline]#We# [.doubleunderline]#cannot predict# yet how exotic species spread through the environment and how they transform natural communities.
====

.Solution
[%collapsible]
====
[.underline]#We# still [.doubleunderline]#cannot predict# with certainty how an exotic species will spread or transform a natural community.
====
--
+
. The [.underline]#amount# of magmatism that accompanies the extension and rupture of the continental lithosphere [.doubleunderline]#varies# dramatically at rifts and margins around the world.
+
--
.My revision
[%collapsible]
====
As the continental lithosphere extends and ruptures, the accompanying magma [.underline]#flow# [.doubleunderline]#varies# dramatically at rifts and margins around the world.
====

.Solution
[%collapsible]
====
When the continental lithosphere extends and ruptures at rifts and margins, the [.underline]#amount# of accompanying magmatism [.doubleunderline]#varies# dramatically.
====
--
+
. [.underline]#Pre-migration# of melts vertically to the top of the melting region and then laterally along the base of the extended continental lithosphere [.doubleunderline]#would focus# melts toward the eastern part of the basin.
+
--
.My revision
[%collapsible]
====
* If melts migrated to the top of the melting region and then along the base of the continental lithosphere, [.underline]#they# [.doubleunderline]#would focus# towards the eastern part of the basin.
* [.underline]#Melts# [.doubleunderline]#would focus# toward the eastern part of the basin if they migrated to the top of the melting region and then along the base of the continental lithosphere.
====

.Solution
[%collapsible]
====
[.underline]#Melts# [.doubleunderline]#migrate# vertically to the top of the melting region, then laterally along the base of the extended continental lithosphere toward the eastern part of the basin.
====
--
+
. Pre-treatment of tenocytes with different concentrations of wortmannin (1, 10, and 20 nM) for 1 h, treated with curcumin (5 μM) for 4 h, and then treated with IL-1β for 1 h, inhibited the IL-1β-induced NF-κB activation.
+
--
.My revision
[%collapsible]
====
[.underline]#We# [.doubleunderline]#prevented# IL-1β from activating NF-κB in tenocytes by treating them with different wortmannin concentrations (1, 10, and 20 nM) for 1 h, curcumin (5 μM) for 4 h, and then IL-1β for 1 h.
====

.Solution
[%collapsible]
====
[.underline]#We# [.doubleunderline]#inhibited# the IL-1β-induced NF-κB activation by treating tenocytes with wortmannin (1, 10, and 20 nM) for 1h, followed by curcumin (5μM) for 4h, and then IL-1β for 1 h.
====
--
