name: Pull request
description: Create a pull request to add new features.
title: "[PR]: "
assignees:
  - gmarti-web
body:
  - type: input
    id: issue
    attributes:
      label: "Issue #"
      description: Enter the issue number for this PR.
      validations:
        required: true
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Enter your comments for this PR.
      validations:
        required: true
