title: GM Blog
title_separator: "|"
subtitle: Personal blog and portfolio
email: greg.martinez44@gmail.com
description: My personal blog and portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gmarti-web.github.io"
github_username:  gmarti-web
lang: en
local: en-US
name: Greg Martinez
breadcrumbs: true
logo: /assets/favicon/favicon.svg
timezone: America/Los_Angeles

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - asciidoctor
  - jekyll-asciidoc
  - jekyll-archives
  - jekyll-feed
  - jekyll-octicons
  - jekyll-include-cache
  - jekyll-paginate

include: ["_pages"]

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .ruby-version
  - scripts/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

show_excerpts: true
enable_copy_code_button: true
words_per_minute: 120
search: true
lunr:
  search_within_pages: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      show_date: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: single
      author_profile: false
      show_date: true
      toc: true
      toc_label: Table of contents
      toc_icon: cog
      toc_sticky: true
      sort_by: order
      read_time: true

author:
  name : Greg Martinez
  email: greg.martinez44@gmail.com
  bio: Data and cloud engineer with a passion for good documentation.
  location: Seattle, WA
  avatar: /assets/bio-avatar.png
  links:
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/greg-martinez44"

pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'  # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

asciidoc:
  processor: asciidoctor
asciidoctor:
  attributes:
    icons: font
    stylesdir: /assets/css
    source-highlighter: pygments
