name: Check readability

on:
  push:
  workflow_dispatch:

jobs:
  check_readability:
    runs-on: ubuntu-latest
    name: Check readability
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout main repo
        id: main
        uses: actions/checkout@v4
      - name: Checkout ReadabilityChecker repo
        id: readabilitychecker
        uses: actions/checkout@v4
        with:
          repository: 'greg-martinez44/ReadabilityChecker'
          path: 'ReadabilityChecker/'
      - name: Run the ReadabilityChecker action
        id: checkerresult
        uses: './ReadabilityChecker/'
        with:
          markdown-file: './_pages/about.md'
      - name: Echo grade level
        run: echo "The Flesch-Kincaid grade level is ${{ steps.checkerresult.outputs.fkgl }}"
      - name: Echo reading ease
        run: echo "The Flesch Reading ease is ${{ steps.checkresult.outputs.fre }}"
