name: Validate front matter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - '**.md'
      - '**.adoc'

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Markdown files
        run: |
          validate_front_matter() {
              local file="$1"

              # Check if the file exists
              if [[ ! -f "$file" ]]; then
                  echo "Error: File does not exist." >&2
                  return 1
              fi

              # Check for a front matter section (delimited by ---)
              if ! awk 'NR==1 && /^---$/ {found=1; next} /^---$/ && found {exit 0} END {exit !found}' "$file"; then
                  echo "Error: Front matter section not found." >&2
                  return 1
              fi

              # Check for a title field in the front matter
              if ! grep -q "^title:" "$file"; then
                  echo "Error: 'title' attribute not found in front matter." >&2
                  return 1
              fi

              # Check for a last_modified_at field
              if ! grep -q "^last_modified_at:" "$file"; then
                  echo "Error: 'last_modified_at' field not found in front matter." >&2
                  return 1
              fi

              # Check if last_modified_at matches the current date (YYYY-mm-dd format)
              local current_date=$(date +"%Y-%m-%d")
              if ! grep -q "^last_modified_at: $current_date" "$file"; then
                  echo "Error: 'last_modified_at' field does not match the current date ($current_date)." >&2
                  return 1
              fi

              echo "Validation passed: The Markdown file is properly formatted."
              return 0
          }

          # Run the validation on all Markdown files
          for file in *.md; do
            validate_front_matter "$file" || exit 1
          done

      - name: Validate AsciiDoc files
        run: |
          validate_and_update_front_matter() {
              local file="$1"

              if [[ ! -f "$file" ]]; then
                  echo "Error: File does not exist." >&2
                  return 1
              fi

              # Check for a front matter section (delimited by : or key-value pairs)
              if ! grep -q "^= \w.*$" "$file"; then
                  echo "Error: 'title' parameter not found in front matter." >&2
                  return 1
              fi

              if ! grep -q ":page-last_modified_at:" "$file"; then
                  echo "Error: 'last-modified' field not found in front matter." >&2
                  return 1
              fi

              local current_date=$(date +"%Y-%m-%d")
              if ! grep -q "^:page-last_modified_at: $current_date" "$file"; then
                  echo "Error: 'last-modified' field does not match the current date ($current_date)." >&2
                  return 1
              fi

              echo "Validation passed: The AsciiDoc file is properly formatted."
              return 0
          }

          # Run the validation on all AsciiDoc files
          for file in *.adoc; do
            validate_and_update_front_matter "$file" || exit 1
          done
