name: reviewdog
on:
  pull_request:
  workflow_dispatch:

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Define the vale StylesPath
        run:
          stylespath="StylesPath = .github/styles"
          sed -ie 'li${stylespath}\' .vale.ini
      - uses: errata-ai/vale-action@v2.1.1
