name: reviewdog
on:
  pull_request:
  workflow_dispatch:

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - id: install asciidoctor
        run: |
          sudo apt install asciidoctor -y
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
